version: '3.8'

services:
  server:
    build: ../part_5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
    command: /bin/sh -c "mkdir -p /var/run/nginx && nginx -g 'daemon off;'"
